language: node_js
node_js:
  - 12
services:
  - docker

## pre-testing install
install:
  - echo "nothing to be installed"

## scripts to be run:
before_script:
  - echo "no test"

 ## Build   
script:
  - docker --version
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user   
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy

## Tagging
  - docker tag udagram-api-feed ekram321/udagram-api-feed:v5
  - docker tag udagram-api-user ekram321/udagram-api-user:v5
  - docker tag udagram-frontend ekram321/udagram-frontend:v1
  - docker tag udagram-reverseproxy ekram321/udagram-reverseproxy:v5

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ekram321/udagram-api-feed:v5
  - docker push ekram321/udagram-api-user:v5
  - docker push udagram-frontend:v1
  - docker push ekram321/udagram-reverseproxy:v5
