language: node_js
node_js:
  - 12
services:
  - docker

## pre-testing install
install:
  - echo "nothing to be installed"

## scripts to be run:
before_script:
  - echo "no test"

 ## Build   
script:
  - docker --version
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user   
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy

## Tagging
  - docker tag udagram-api-feed ekram321/udagram-api-feed:v4
  - docker tag udagram-api-user ekram321/udagram-api-user:v4
  - docker tag udagram-frontend ekram321/udagram-frontend:v2
  - docker tag reverseproxy ekram321/reverseproxy:v4a

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ekram321/udagram-api-feed:v4
  - docker push ekram321/udagram-api-user:v4
  - docker push udagram-frontend:v2
  - docker push ekram321/reverseproxy:v4a
